#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/home/aza/The_Hive"
LOCK_FILE="$PROJECT_DIR/data/checkpoints/nightly_training.lock"
LOCK_DIR="$PROJECT_DIR/data/checkpoints/nightly_training.lock.d"
SUMMARY_FILE="$PROJECT_DIR/data/checkpoints/nightly_training_summary.json"
cd "$PROJECT_DIR"

if [ -f .env ]; then
  eval "$(
    python3 - <<'PY'
from __future__ import annotations

import pathlib
import shlex

env_path = pathlib.Path(".env")
for raw_line in env_path.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    key, value = line.split("=", 1)
    key = key.strip()
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    print(f"export {key}={shlex.quote(value)}")
PY
  )"
fi


VLLM_STOPPED=0
COMFYUI_STOPPED=0
RUN_TRIGGER="${TRAINING_RUN_TRIGGER:-manual}"

mkdir -p "$(dirname "$LOCK_FILE")"

emit_training_log() {
  local level="$1"
  local source="$2"
  shift 2
  local message="$*"
  PYTHONPATH="$PROJECT_DIR/src/eva-lab:$PROJECT_DIR/src/shared"   TRAINING_LOG_LEVEL="$level"   TRAINING_LOG_SOURCE="$source"   TRAINING_LOG_MESSAGE="$message"   python3 - <<'PY'
from __future__ import annotations

import os

from eva_lab.training_status import append_training_log

append_training_log(
    os.environ.get("TRAINING_LOG_MESSAGE", ""),
    level=os.environ.get("TRAINING_LOG_LEVEL", "INFO"),
    source=os.environ.get("TRAINING_LOG_SOURCE", "launcher"),
)
PY
}

emit_launcher_state() {
  local phase="$1"
  local vllm_state="${2:-}"
  local comfyui_state="${3:-}"
  local trainer_container="${4:-}"
  PYTHONPATH="$PROJECT_DIR/src/eva-lab:$PROJECT_DIR/src/shared"   TRAINING_LAUNCHER_PHASE="$phase"   TRAINING_VLLM_STATE="$vllm_state"   TRAINING_COMFYUI_STATE="$comfyui_state"   TRAINING_TRAINER_CONTAINER="$trainer_container"   TRAINING_REMOTE_PID="$$"   TRAINING_RUN_TRIGGER="$RUN_TRIGGER"   python3 - <<'PY'
from __future__ import annotations

import os

from eva_lab.training_status import set_training_launcher_state

set_training_launcher_state(
    phase=os.environ.get("TRAINING_LAUNCHER_PHASE") or None,
    vllm_state=os.environ.get("TRAINING_VLLM_STATE") or None,
    comfyui_state=os.environ.get("TRAINING_COMFYUI_STATE") or None,
    trainer_container=os.environ.get("TRAINING_TRAINER_CONTAINER") or None,
    remote_pid=os.environ.get("TRAINING_REMOTE_PID") or None,
    trigger=os.environ.get("TRAINING_RUN_TRIGGER") or None,
)
PY
}

write_skip_marker() {
  local skip_reason="$1"
  SUMMARY_FILE="$SUMMARY_FILE" LOCK_FILE="$LOCK_FILE" RUN_TRIGGER="$RUN_TRIGGER" SKIP_REASON="$skip_reason" python3 - <<'PY'
from __future__ import annotations

import json
import os
import sys
from datetime import datetime
from pathlib import Path

summary_file = Path(os.environ["SUMMARY_FILE"])
lock_file = Path(os.environ["LOCK_FILE"])
skip_reason = os.environ.get("SKIP_REASON", "run_already_active")
run_trigger = os.environ.get("RUN_TRIGGER", "unknown")
project_dir = Path("/home/aza/The_Hive")
for candidate in (project_dir / "src/eva-lab", project_dir / "src/shared"):
    candidate_str = str(candidate)
    if candidate_str not in sys.path:
        sys.path.insert(0, candidate_str)

payload: dict[str, object]
if summary_file.exists():
    try:
        loaded = json.loads(summary_file.read_text(encoding="utf-8"))
        payload = loaded if isinstance(loaded, dict) else {}
    except Exception:
        payload = {}
else:
    payload = {}

event = {
    "trigger": run_trigger,
    "reason": skip_reason,
    "timestamp": datetime.now().isoformat(),
}
if lock_file.exists():
    try:
        lock_payload = json.loads(lock_file.read_text(encoding="utf-8"))
        event["lock"] = lock_payload if isinstance(lock_payload, dict) else {}
    except Exception:
        event["lock"] = {"path": str(lock_file)}

skip_events = list(payload.get("skip_events") or [])
skip_events.append(event)
payload["skip_events"] = skip_events[-20:]
payload["last_skip_event"] = event
payload.setdefault("strategy", os.environ.get("TRAINING_PROFILE", "smart"))
if payload.get("status") in {None, "skipped"}:
    payload["status"] = "skipped"
    payload["finished_at"] = datetime.now().isoformat()
summary_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")

try:
    from eva_lab.training_status import append_training_log, mark_skip_status, set_training_launcher_state

    mark_skip_status(skip_reason, run_trigger, event.get("lock"))
    set_training_launcher_state(last_skip_reason=skip_reason, trigger=run_trigger)
    append_training_log(
        f"Run ignore par le lanceur: {skip_reason}",
        level="WARNING",
        source="launcher",
    )
except Exception:
    pass
PY
}

read_lock_pid() {
  if [ ! -f "$LOCK_FILE" ]; then
    return 1
  fi
  python3 - <<'PY'
from __future__ import annotations

import json
from pathlib import Path

lock_file = Path("/home/aza/The_Hive/data/checkpoints/nightly_training.lock")
try:
    payload = json.loads(lock_file.read_text(encoding="utf-8"))
except Exception:
    print("")
    raise SystemExit(0)

pid = payload.get("pid")
print(pid if isinstance(pid, int) else "")
PY
}

list_active_trainer_containers() {
  docker ps --format '{{.Names}}' | grep '^the_hive-eva-trainer-run-' || true
}

acquire_lock() {
  local active_trainers
  active_trainers="$(list_active_trainer_containers)"
  if [ -n "$active_trainers" ]; then
    echo "[nightly] Conteneur trainer deja actif. Skip propre."
    printf '%s
' "$active_trainers"
    write_skip_marker "trainer_container_active"
    exit 0
  fi

  if mkdir "$LOCK_DIR" 2>/dev/null; then
    :
  else
    local existing_pid
    existing_pid="$(read_lock_pid || true)"
    if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
      echo "[nightly] Run deja actif (pid=$existing_pid). Skip propre."
      write_skip_marker "run_already_active"
      exit 0
    fi
    echo "[nightly] Verrou nightly obsolete detecte. Nettoyage."
    rm -rf "$LOCK_DIR"
    rm -f "$LOCK_FILE"
    mkdir "$LOCK_DIR"
  fi

  printf '{"pid": %s, "trigger": "%s", "profile": "%s", "started_at": "%s"}\n' \
    "$$" "$RUN_TRIGGER" "${TRAINING_PROFILE:-smart}" "$(date -Iseconds)" > "$LOCK_FILE"
}

release_lock() {
  rm -rf "$LOCK_DIR"
  rm -f "$LOCK_FILE"
}

export TRAINING_PROFILE="${TRAINING_PROFILE:-smart}"
export TRAINING_AUTOMATION_MODE="${TRAINING_AUTOMATION_MODE:-smart}"
export TRAINING_RUN_LOCK_ALREADY_HELD=1

if [ "$TRAINING_PROFILE" = "research" ]; then
  echo "[nightly] Profil research actif: priorite a l'entrainement massif"
  : "${RUN_TRAIN_DREAMER:=0}"
  : "${MUZERO_MAX_SYMBOLS:=0}"
  : "${ARENA_MAX_SYMBOLS:=0}"
  : "${MUZERO_GAMES_PER_SYMBOL:=20}"
  : "${ARENA_GAMES_PER_SYMBOL:=8}"
  : "${ARENA_MIN_GAMES:=24}"
  : "${ARENA_MIN_SYMBOLS:=6}"
  : "${MUZERO_TRAINING_STEPS:=32000}"
fi

export VLLM_GPU_DEVICE="${VLLM_GPU_DEVICE:-0}"
export TRAINING_GPU_DEVICE="${TRAINING_GPU_DEVICE:-1}"
if [ -z "${NIGHTLY_KEEP_VLLM:-}" ]; then
  if [ "$VLLM_GPU_DEVICE" != "$TRAINING_GPU_DEVICE" ]; then
    export NIGHTLY_KEEP_VLLM="1"
  else
    export NIGHTLY_KEEP_VLLM="0"
  fi
fi
export NIGHTLY_DEFER_VLLM_RESTART="${NIGHTLY_DEFER_VLLM_RESTART:-0}"
export NIGHTLY_STOP_COMFYUI="${NIGHTLY_STOP_COMFYUI:-0}"
acquire_lock
emit_launcher_state "preflight" "online" "online"
emit_training_log INFO launcher "Verification des services critiques avant entrainement."

echo "[nightly] Verification des services critiques avant entrainement"
docker ps --format '{{.Names}} {{.Status}}' | grep -E 'the_hive-(lab|vllm|redis|neo4j|mosquitto)' || true

if [ "$NIGHTLY_KEEP_VLLM" = "1" ]; then
  echo "[nightly] vLLM conserve en ligne grace a la separation GPU"
  emit_launcher_state "preflight" "online" "$([ "$NIGHTLY_STOP_COMFYUI" = "1" ] && echo stop_requested || echo online)"
  emit_training_log INFO launcher "vLLM conserve en ligne pour ce run grace a la separation GPU ou a un override explicite."
else
  echo "[nightly] Arret temporaire de vLLM pour liberer le GPU"
  docker update --restart=no the_hive-vllm-1 >/dev/null 2>&1 || true
  docker compose stop vllm || true
  VLLM_STOPPED=1
  emit_launcher_state "preflight" "stopped_for_training" "$([ "$NIGHTLY_STOP_COMFYUI" = "1" ] && echo stop_requested || echo online)"
  emit_training_log INFO launcher "vLLM arrete volontairement pour liberer le GPU et son auto-redemarrage est neutralise pendant le run."
fi

if [ "$NIGHTLY_STOP_COMFYUI" = "1" ]; then
  echo "[nightly] Arret temporaire de ComfyUI"
  docker compose stop comfyui || true
  COMFYUI_STOPPED=1
  emit_launcher_state "preflight" "$([ "$VLLM_STOPPED" = "1" ] && echo stopped_for_training || echo online)" "stopped_for_training"
  emit_training_log INFO launcher "ComfyUI arrete temporairement pour le run."
fi

cleanup() {
  echo "[nightly] Redemarrage des services GPU"
  cd "$PROJECT_DIR"
  if [ "$COMFYUI_STOPPED" = "1" ]; then
    docker compose up -d comfyui >/dev/null 2>&1 || true
  fi
  if [ "$VLLM_STOPPED" = "1" ]; then
    docker update --restart=unless-stopped the_hive-vllm-1 >/dev/null 2>&1 || true
    if [ "$NIGHTLY_DEFER_VLLM_RESTART" = "1" ]; then
      echo "[nightly] Redemarrage de vLLM differe jusqu'a la fin de la sequence"
      emit_launcher_state "cleanup" "deferred" "$([ "$COMFYUI_STOPPED" = "1" ] && echo restarting || echo online)"
      emit_training_log INFO launcher "Redemarrage de vLLM differe a la fin de la sequence Gold."
      return
    fi
    docker compose up -d vllm >/dev/null 2>&1 || true
    echo "[nightly] Attente de vLLM apres redemarrage"
    emit_launcher_state "cleanup" "restarting" "$([ "$COMFYUI_STOPPED" = "1" ] && echo restarting || echo online)"
    emit_training_log INFO launcher "Redemarrage de vLLM apres entrainement."
    for attempt in $(seq 1 18); do
      if curl -fsS --max-time 5 http://127.0.0.1:8000/health >/dev/null 2>&1; then
        echo "[nightly] vLLM operationnel"
        emit_launcher_state "cleanup" "online" "$([ "$COMFYUI_STOPPED" = "1" ] && echo online || echo online)"
        emit_training_log INFO launcher "vLLM de nouveau operationnel apres le run."
        break
      fi
      if [ "$attempt" -eq 6 ]; then
        echo "[nightly] vLLM encore indisponible, redemarrage complementaire"
        docker compose restart vllm >/dev/null 2>&1 || true
      fi
      sleep 10
    done
  fi
  emit_launcher_state "idle" "online" "online"
  release_lock
}
trap cleanup EXIT

export RUN_TRAIN_GNN="${RUN_TRAIN_GNN:-1}"
export RUN_TRAIN_MUZERO="${RUN_TRAIN_MUZERO:-1}"
export RUN_TRAIN_DREAMER="${RUN_TRAIN_DREAMER:-0}"
export TRAINING_ENGINE="${TRAINING_ENGINE:-}"
export TRAINING_TRIAL_MODE="${TRAINING_TRIAL_MODE:-}"
export TRAINING_TRIAL_COST_PROFILE="${TRAINING_TRIAL_COST_PROFILE:-}"
export REBUILD_TRAINER_IMAGE="${REBUILD_TRAINER_IMAGE:-1}"
export MUZERO_HORIZONS="${MUZERO_HORIZONS:-scalp,intraday,swing}"
export DREAMER_HORIZON="${DREAMER_HORIZON:-}"
export DREAMER_DEFAULT_HORIZON="${DREAMER_DEFAULT_HORIZON:-}"
export DREAMER_EPOCHS="${DREAMER_EPOCHS:-1500}"
export TRAIN_GNN_EPOCHS="${TRAIN_GNN_EPOCHS:-500}"
export TRAIN_GNN_BATCH_SIZE="${TRAIN_GNN_BATCH_SIZE:-64}"
export TRAIN_GNN_CHECKPOINT_EVERY="${TRAIN_GNN_CHECKPOINT_EVERY:-25}"
export TRAIN_GNN_SYMBOLS="${TRAIN_GNN_SYMBOLS:-}"
export TRAIN_GNN_FOCUS_SYMBOL="${TRAIN_GNN_FOCUS_SYMBOL:-}"
export TRAIN_GNN_CONTEXT_SYMBOLS="${TRAIN_GNN_CONTEXT_SYMBOLS:-}"
export TRAIN_GNN_DEPLOYMENT_CLASS="${TRAIN_GNN_DEPLOYMENT_CLASS:-consultative}"
export MUZERO_TRAINING_STEPS="${MUZERO_TRAINING_STEPS:-24000}"
export MUZERO_GAMES_PER_SYMBOL="${MUZERO_GAMES_PER_SYMBOL:-12}"
export MUZERO_BATCH_SIZE="${MUZERO_BATCH_SIZE:-32}"
export MUZERO_NUM_SIMULATIONS="${MUZERO_NUM_SIMULATIONS:-100}"
export MUZERO_COLLECTION_NUM_SIMULATIONS="${MUZERO_COLLECTION_NUM_SIMULATIONS:-32}"
export MUZERO_COLLECTION_NUM_SIMULATIONS_METALS="${MUZERO_COLLECTION_NUM_SIMULATIONS_METALS:-160}"
export MUZERO_COLLECTION_NUM_SIMULATIONS_XAUUSD="${MUZERO_COLLECTION_NUM_SIMULATIONS_XAUUSD:-128}"
export MUZERO_ROOT_EXPLORATION_FRACTION="${MUZERO_ROOT_EXPLORATION_FRACTION:-0.25}"
export MUZERO_PB_C_INIT="${MUZERO_PB_C_INIT:-1.25}"
export MUZERO_REANALYZE_EVERY_STEPS="${MUZERO_REANALYZE_EVERY_STEPS:-500}"
export MUZERO_REANALYZE_MAX_GAMES="${MUZERO_REANALYZE_MAX_GAMES:-16}"
export MUZERO_REANALYZE_MAX_POSITIONS_PER_GAME="${MUZERO_REANALYZE_MAX_POSITIONS_PER_GAME:-24}"
export MUZERO_REANALYZE_NUM_SIMULATIONS="${MUZERO_REANALYZE_NUM_SIMULATIONS:-16}"
export MUZERO_MAX_MOVES="${MUZERO_MAX_MOVES:-300}"
export MUZERO_RANDOMIZE_EPISODE_START="${MUZERO_RANDOMIZE_EPISODE_START:-1}"
export MUZERO_EPISODE_WARMUP_BARS="${MUZERO_EPISODE_WARMUP_BARS:-100}"
export MUZERO_COLLECTION_HEARTBEAT_EVERY_STEPS="${MUZERO_COLLECTION_HEARTBEAT_EVERY_STEPS:-25}"
export MUZERO_COLLECTION_HEARTBEAT_EVERY_SECONDS="${MUZERO_COLLECTION_HEARTBEAT_EVERY_SECONDS:-30}"
export MUZERO_COLLECTION_MAX_EPISODE_SECONDS="${MUZERO_COLLECTION_MAX_EPISODE_SECONDS:-300}"
export MUZERO_COLLECTION_MAX_EPISODE_SECONDS_METALS="${MUZERO_COLLECTION_MAX_EPISODE_SECONDS_METALS:-180}"
export MUZERO_COLLECTION_MAX_EPISODE_SECONDS_XAUUSD="${MUZERO_COLLECTION_MAX_EPISODE_SECONDS_XAUUSD:-150}"
export MUZERO_COLLECTION_MAX_MOVES="${MUZERO_COLLECTION_MAX_MOVES:-180}"
export MUZERO_COLLECTION_MAX_MOVES_METALS="${MUZERO_COLLECTION_MAX_MOVES_METALS:-96}"
export MUZERO_COLLECTION_MAX_MOVES_XAUUSD="${MUZERO_COLLECTION_MAX_MOVES_XAUUSD:-72}"
export MUZERO_COLLECTION_MAX_STEP_SECONDS="${MUZERO_COLLECTION_MAX_STEP_SECONDS:-20}"
export MUZERO_COLLECTION_PARALLEL_GAMES="${MUZERO_COLLECTION_PARALLEL_GAMES:-1}"
export MUZERO_DIRECTIONAL_CURRICULUM_SOFT_END_STEP="${MUZERO_DIRECTIONAL_CURRICULUM_SOFT_END_STEP:-8000}"
export MUZERO_DIRECTIONAL_CURRICULUM_END_STEP="${MUZERO_DIRECTIONAL_CURRICULUM_END_STEP:-15000}"
export MUZERO_SOFT_REWARD_EARLY_END_STEP="${MUZERO_SOFT_REWARD_EARLY_END_STEP:-4000}"
export MUZERO_SOFT_REWARD_MID_END_STEP="${MUZERO_SOFT_REWARD_MID_END_STEP:-10000}"
export MUZERO_SOFT_REWARD_PENALTY_SCALE_EARLY="${MUZERO_SOFT_REWARD_PENALTY_SCALE_EARLY:-0.45}"
export MUZERO_SOFT_REWARD_PENALTY_SCALE_MID="${MUZERO_SOFT_REWARD_PENALTY_SCALE_MID:-0.65}"
export MUZERO_SOFT_REWARD_PENALTY_SCALE_LATE="${MUZERO_SOFT_REWARD_PENALTY_SCALE_LATE:-0.85}"
export MUZERO_SOFT_REWARD_BONUS_SCALE_EARLY="${MUZERO_SOFT_REWARD_BONUS_SCALE_EARLY:-1.15}"
export MUZERO_SOFT_REWARD_BONUS_SCALE_MID="${MUZERO_SOFT_REWARD_BONUS_SCALE_MID:-1.00}"
export MUZERO_SOFT_REWARD_BONUS_SCALE_LATE="${MUZERO_SOFT_REWARD_BONUS_SCALE_LATE:-0.95}"
export MUZERO_EXIT_REWARD_EARLY_END_STEP="${MUZERO_EXIT_REWARD_EARLY_END_STEP:-4000}"
export MUZERO_EXIT_REWARD_MID_END_STEP="${MUZERO_EXIT_REWARD_MID_END_STEP:-10000}"
export MUZERO_EXIT_REWARD_SCALE_EARLY="${MUZERO_EXIT_REWARD_SCALE_EARLY:-0.35}"
export MUZERO_EXIT_REWARD_SCALE_MID="${MUZERO_EXIT_REWARD_SCALE_MID:-0.55}"
export MUZERO_EXIT_REWARD_SCALE_LATE="${MUZERO_EXIT_REWARD_SCALE_LATE:-1.00}"
export MUZERO_POLICY_PRECHECK_STEP="${MUZERO_POLICY_PRECHECK_STEP:-12000}"
export MUZERO_POLICY_PRECHECK_WINDOW_SIZE="${MUZERO_POLICY_PRECHECK_WINDOW_SIZE:-500}"
export MUZERO_POLICY_PRECHECK_MAX_LOSS_POL="${MUZERO_POLICY_PRECHECK_MAX_LOSS_POL:-5.8}"
export MUZERO_POLICY_PRECHECK_MAX_LOSS_POL_PER_HEAD="${MUZERO_POLICY_PRECHECK_MAX_LOSS_POL_PER_HEAD:-1.08}"
export MUZERO_POLICY_PRECHECK_MIN_TOP1_SHARE="${MUZERO_POLICY_PRECHECK_MIN_TOP1_SHARE:-0.75}"
export MUZERO_POLICY_PRECHECK_MAX_POLICY_ENTROPY="${MUZERO_POLICY_PRECHECK_MAX_POLICY_ENTROPY:-1.0}"
export MUZERO_POLICY_PRECHECK_MAX_ROOT_MASK_RATE="${MUZERO_POLICY_PRECHECK_MAX_ROOT_MASK_RATE:-0.02}"
export MUZERO_POLICY_PRECHECK_MAX_POST_VETO_RATE="${MUZERO_POLICY_PRECHECK_MAX_POST_VETO_RATE:-0.01}"
export MUZERO_POLICY_PRECHECK_MIN_BALANCED_EPISODE_RATE="${MUZERO_POLICY_PRECHECK_MIN_BALANCED_EPISODE_RATE:-0.85}"
export MUZERO_POLICY_PRECHECK_MIN_LONG_ENTRY_SHARE="${MUZERO_POLICY_PRECHECK_MIN_LONG_ENTRY_SHARE:-0.35}"
export MUZERO_POLICY_PRECHECK_MIN_SHORT_ENTRY_SHARE="${MUZERO_POLICY_PRECHECK_MIN_SHORT_ENTRY_SHARE:-0.35}"
export MUZERO_POLICY_PRECHECK_MIN_CLOSE_QUALITY_SCORE="${MUZERO_POLICY_PRECHECK_MIN_CLOSE_QUALITY_SCORE:-0.40}"
export MUZERO_POLICY_PRECHECK_MIN_SPLIT_EFFICIENCY="${MUZERO_POLICY_PRECHECK_MIN_SPLIT_EFFICIENCY:-0.35}"
export MUZERO_POLICY_PRECHECK_MIN_PYRAMID_EFFICIENCY="${MUZERO_POLICY_PRECHECK_MIN_PYRAMID_EFFICIENCY:-0.35}"
export MUZERO_POLICY_PRECHECK_MIN_SLBE_CAPTURE_RATE="${MUZERO_POLICY_PRECHECK_MIN_SLBE_CAPTURE_RATE:-0.45}"
export MUZERO_POLICY_PRECHECK_MAX_HOLD_DRAG_SCORE="${MUZERO_POLICY_PRECHECK_MAX_HOLD_DRAG_SCORE:-0.10}"
export MUZERO_POLICY_PRECHECK_MIN_GOOD_CLOSE_SYMBOLS="${MUZERO_POLICY_PRECHECK_MIN_GOOD_CLOSE_SYMBOLS:-5}"
export MUZERO_POLICY_PRECHECK_MIN_SYMBOL_CLOSE_QUALITY_SCORE="${MUZERO_POLICY_PRECHECK_MIN_SYMBOL_CLOSE_QUALITY_SCORE:-0.25}"
export MUZERO_POLICY_PRECHECK_MIN_SYMBOL_CLOSE_EVENTS="${MUZERO_POLICY_PRECHECK_MIN_SYMBOL_CLOSE_EVENTS:-6}"
export MUZERO_POLICY_SCREEN_MAX_LOSS_POL="${MUZERO_POLICY_SCREEN_MAX_LOSS_POL:-6.6}"
export MUZERO_POLICY_SCREEN_MAX_LOSS_POL_PER_HEAD="${MUZERO_POLICY_SCREEN_MAX_LOSS_POL_PER_HEAD:-1.20}"
export MUZERO_POLICY_SCREEN_MIN_TOP1_SHARE="${MUZERO_POLICY_SCREEN_MIN_TOP1_SHARE:-0.88}"
export MUZERO_POLICY_SCREEN_MAX_POLICY_ENTROPY="${MUZERO_POLICY_SCREEN_MAX_POLICY_ENTROPY:-0.45}"
export MUZERO_POLICY_SCREEN_MAX_ROOT_MASK_RATE="${MUZERO_POLICY_SCREEN_MAX_ROOT_MASK_RATE:-0.05}"
export MUZERO_POLICY_SCREEN_MAX_POST_VETO_RATE="${MUZERO_POLICY_SCREEN_MAX_POST_VETO_RATE:-0.01}"
export MUZERO_POLICY_SCREEN_MIN_BALANCED_EPISODE_RATE="${MUZERO_POLICY_SCREEN_MIN_BALANCED_EPISODE_RATE:-0.85}"
export MUZERO_POLICY_SCREEN_MIN_LONG_ENTRY_SHARE="${MUZERO_POLICY_SCREEN_MIN_LONG_ENTRY_SHARE:-0.35}"
export MUZERO_POLICY_SCREEN_MIN_SHORT_ENTRY_SHARE="${MUZERO_POLICY_SCREEN_MIN_SHORT_ENTRY_SHARE:-0.35}"
export MUZERO_ARENA_SCREEN_RECENT_STEPS="${MUZERO_ARENA_SCREEN_RECENT_STEPS:-2500}"
export MUZERO_ARENA_SCREEN_CANDIDATE_COUNT="${MUZERO_ARENA_SCREEN_CANDIDATE_COUNT:-5}"
export MUZERO_ARENA_SCREEN_WINDOW_SIZE="${MUZERO_ARENA_SCREEN_WINDOW_SIZE:-500}"
export MUZERO_ARENA_SCREEN_GAMES_PER_SYMBOL="${MUZERO_ARENA_SCREEN_GAMES_PER_SYMBOL:-4}"
export MUZERO_ARENA_SCREEN_MIN_GAMES="${MUZERO_ARENA_SCREEN_MIN_GAMES:-14}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOLS="${MUZERO_ARENA_SCREEN_MIN_SYMBOLS:-7}"
export MUZERO_ARENA_SCREEN_MIN_PROFIT_FACTOR="${MUZERO_ARENA_SCREEN_MIN_PROFIT_FACTOR:-1.20}"
export MUZERO_ARENA_SCREEN_MIN_RETURN_PCT="${MUZERO_ARENA_SCREEN_MIN_RETURN_PCT:-0.0}"
export MUZERO_ARENA_SCREEN_MIN_EXPECTANCY_PCT="${MUZERO_ARENA_SCREEN_MIN_EXPECTANCY_PCT:-0.0}"
export MUZERO_ARENA_SCREEN_MIN_POSITIVE_EPISODE_RATE="${MUZERO_ARENA_SCREEN_MIN_POSITIVE_EPISODE_RATE:-55.0}"
export MUZERO_ARENA_SCREEN_MAX_HOLD_DRAG_SCORE="${MUZERO_ARENA_SCREEN_MAX_HOLD_DRAG_SCORE:-0.80}"
export MUZERO_ARENA_SCREEN_MIN_CLOSE_QUALITY_SCORE="${MUZERO_ARENA_SCREEN_MIN_CLOSE_QUALITY_SCORE:-0.35}"
export MUZERO_ARENA_SCREEN_MIN_SPLIT_OPPORTUNITIES="${MUZERO_ARENA_SCREEN_MIN_SPLIT_OPPORTUNITIES:-3}"
export MUZERO_ARENA_SCREEN_MIN_SPLIT_EFFICIENCY="${MUZERO_ARENA_SCREEN_MIN_SPLIT_EFFICIENCY:-0.35}"
export MUZERO_ARENA_SCREEN_MIN_SPLIT_RUNNER_CAPTURE_RATE="${MUZERO_ARENA_SCREEN_MIN_SPLIT_RUNNER_CAPTURE_RATE:-0.20}"
export MUZERO_ARENA_SCREEN_MIN_PYRAMID_OPPORTUNITIES="${MUZERO_ARENA_SCREEN_MIN_PYRAMID_OPPORTUNITIES:-3}"
export MUZERO_ARENA_SCREEN_MIN_PYRAMID_EFFICIENCY="${MUZERO_ARENA_SCREEN_MIN_PYRAMID_EFFICIENCY:-0.35}"
export MUZERO_ARENA_SCREEN_MIN_PYRAMID_EXIT_CAPTURE_RATE="${MUZERO_ARENA_SCREEN_MIN_PYRAMID_EXIT_CAPTURE_RATE:-0.20}"
export MUZERO_ARENA_SCREEN_MIN_SLBE_TRIGGERED="${MUZERO_ARENA_SCREEN_MIN_SLBE_TRIGGERED:-3}"
export MUZERO_ARENA_SCREEN_MIN_SLBE_CAPTURE_RATE="${MUZERO_ARENA_SCREEN_MIN_SLBE_CAPTURE_RATE:-0.30}"
export MUZERO_ARENA_SCREEN_MIN_PROFITABLE_SYMBOLS="${MUZERO_ARENA_SCREEN_MIN_PROFITABLE_SYMBOLS:-5}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_PROFIT_FACTOR="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_PROFIT_FACTOR:-1.0}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_RETURN_PCT="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_RETURN_PCT:-0.0}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_SPLIT_EFFICIENCY="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_SPLIT_EFFICIENCY:-0.20}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_SPLIT_RUNNER_CAPTURE_RATE="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_SPLIT_RUNNER_CAPTURE_RATE:-0.20}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_PYRAMID_EXIT_CAPTURE_RATE="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_PYRAMID_EXIT_CAPTURE_RATE:-0.20}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_SLBE_CAPTURE_RATE="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_SLBE_CAPTURE_RATE:-0.25}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_CLOSE_QUALITY_SCORE="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_CLOSE_QUALITY_SCORE:-0.20}"
export MUZERO_ARENA_SCREEN_MIN_SYMBOL_CLOSE_EVENTS="${MUZERO_ARENA_SCREEN_MIN_SYMBOL_CLOSE_EVENTS:-6}"
export MUZERO_HOLD_DRAG_PROFIT_FLOOR="${MUZERO_HOLD_DRAG_PROFIT_FLOOR:-}"
export MUZERO_HOLD_DRAG_GRACE_STEPS="${MUZERO_HOLD_DRAG_GRACE_STEPS:-}"
export MUZERO_HOLD_DRAG_PENALTY_CAP="${MUZERO_HOLD_DRAG_PENALTY_CAP:-}"
export MUZERO_PYRAMID_STRONG_TREND_REWARD_BONUS="${MUZERO_PYRAMID_STRONG_TREND_REWARD_BONUS:-}"
export MUZERO_SPLIT_POST_SPLIT_SLBE_BONUS="${MUZERO_SPLIT_POST_SPLIT_SLBE_BONUS:-}"
export MUZERO_SPLIT_SOFT_PARTIAL_VALUE_FLOOR="${MUZERO_SPLIT_SOFT_PARTIAL_VALUE_FLOOR:-}"
export MUZERO_SPLIT_RUNNER_PROFIT_BONUS="${MUZERO_SPLIT_RUNNER_PROFIT_BONUS:-0.45}"
export MUZERO_SPLIT_EARLY_ZONE_PENALTY="${MUZERO_SPLIT_EARLY_ZONE_PENALTY:-0.25}"
export MUZERO_SPLIT_DECORATIVE_PENALTY="${MUZERO_SPLIT_DECORATIVE_PENALTY:-0.15}"
export MUZERO_PYRAMID_EXIT_CAPTURE_BONUS="${MUZERO_PYRAMID_EXIT_CAPTURE_BONUS:-0.35}"
export MUZERO_PYRAMID_BAD_ADD_PENALTY="${MUZERO_PYRAMID_BAD_ADD_PENALTY:-0.35}"
export MUZERO_RUNNER_PROTECTED_EXIT_BONUS="${MUZERO_RUNNER_PROTECTED_EXIT_BONUS:-0.30}"
export MUZERO_RUNNER_HOLD_CAPTURE_BONUS="${MUZERO_RUNNER_HOLD_CAPTURE_BONUS:-0.12}"
export MUZERO_SPLIT_ZONE_CAPTURE_BONUS="${MUZERO_SPLIT_ZONE_CAPTURE_BONUS:-0.18}"
export MUZERO_RUNNER_EXTENSION_CAPTURE_BONUS="${MUZERO_RUNNER_EXTENSION_CAPTURE_BONUS:-0.22}"
export MUZERO_RUNNER_MISSED_EXTENSION_PENALTY="${MUZERO_RUNNER_MISSED_EXTENSION_PENALTY:-0.10}"
export MUZERO_RUNNER_TRADE_COMPLETION_BONUS="${MUZERO_RUNNER_TRADE_COMPLETION_BONUS:-0.40}"
export MUZERO_RUNNER_GIVEBACK_PENALTY="${MUZERO_RUNNER_GIVEBACK_PENALTY:-0.45}"
export MUZERO_RUNNER_GIVEBACK_RATIO_PENALTY="${MUZERO_RUNNER_GIVEBACK_RATIO_PENALTY:-0.35}"
export MUZERO_RUNNER_RETAINED_PROFIT_BONUS="${MUZERO_RUNNER_RETAINED_PROFIT_BONUS:-0.25}"
export MUZERO_PYRAMID_TRADE_COMPLETION_BONUS="${MUZERO_PYRAMID_TRADE_COMPLETION_BONUS:-0.30}"
export MUZERO_PYRAMID_STAGNANT_EXIT_PENALTY="${MUZERO_PYRAMID_STAGNANT_EXIT_PENALTY:-0.25}"
export MUZERO_PYRAMID_HOLD_CAPTURE_BONUS="${MUZERO_PYRAMID_HOLD_CAPTURE_BONUS:-0.10}"
export MUZERO_PYRAMID_ADD_CAPTURE_BONUS="${MUZERO_PYRAMID_ADD_CAPTURE_BONUS:-0.18}"
export MUZERO_PYRAMID_MISSED_ADD_PENALTY="${MUZERO_PYRAMID_MISSED_ADD_PENALTY:-0.12}"
export MUZERO_SLBE_LOCK_PROFIT_RETURN="${MUZERO_SLBE_LOCK_PROFIT_RETURN:-}"
export MUZERO_SLBE_LOCK_PROFIT_BUFFER="${MUZERO_SLBE_LOCK_PROFIT_BUFFER:-}"
export MUZERO_CLOSE_REVERSAL_CLOSE_BONUS="${MUZERO_CLOSE_REVERSAL_CLOSE_BONUS:-}"
export MUZERO_CLOSE_EARLY_PROFIT_CLOSE_PENALTY="${MUZERO_CLOSE_EARLY_PROFIT_CLOSE_PENALTY:-}"
export MUZERO_EXIT_PLAN_HARD_STOP_ATR_MULT="${MUZERO_EXIT_PLAN_HARD_STOP_ATR_MULT:-}"
export MUZERO_EXIT_PLAN_SOFT_TP_ATR_MULT="${MUZERO_EXIT_PLAN_SOFT_TP_ATR_MULT:-}"
export MUZERO_EXIT_PLAN_FULL_TP_ATR_MULT="${MUZERO_EXIT_PLAN_FULL_TP_ATR_MULT:-}"
export MUZERO_EXIT_PLAN_TIME_STOP_STEPS="${MUZERO_EXIT_PLAN_TIME_STOP_STEPS:-}"
export MUZERO_EXIT_PLAN_RUNNER_EXTENSION_ATR_MULT="${MUZERO_EXIT_PLAN_RUNNER_EXTENSION_ATR_MULT:-}"
export MUZERO_EXIT_PLAN_RECOVERY_GRACE_STEPS="${MUZERO_EXIT_PLAN_RECOVERY_GRACE_STEPS:-}"
export MUZERO_MAX_SYMBOLS="${MUZERO_MAX_SYMBOLS:-12}"
export MUZERO_MODEL_FAMILY="${MUZERO_MODEL_FAMILY:-}"
export MUZERO_DATASET_SOURCE="${MUZERO_DATASET_SOURCE:-auto}"
export MUZERO_SYMBOLS="${MUZERO_SYMBOLS:-}"
export MUZERO_SYMBOLS_SCALP="${MUZERO_SYMBOLS_SCALP:-}"
export MUZERO_SYMBOLS_INTRADAY="${MUZERO_SYMBOLS_INTRADAY:-}"
export MUZERO_SYMBOLS_SWING="${MUZERO_SYMBOLS_SWING:-}"
export TRAINING_SYMBOLS="${TRAINING_SYMBOLS:-}"
export ARENA_MAX_SYMBOLS="${ARENA_MAX_SYMBOLS:-12}"
export ARENA_SYMBOLS="${ARENA_SYMBOLS:-}"
export ARENA_SYMBOLS_SCALP="${ARENA_SYMBOLS_SCALP:-}"
export ARENA_SYMBOLS_INTRADAY="${ARENA_SYMBOLS_INTRADAY:-}"
export ARENA_SYMBOLS_SWING="${ARENA_SYMBOLS_SWING:-}"
export ARENA_GAMES_PER_SYMBOL="${ARENA_GAMES_PER_SYMBOL:-6}"
export ARENA_MIN_GAMES="${ARENA_MIN_GAMES:-12}"
export ARENA_MIN_SYMBOLS="${ARENA_MIN_SYMBOLS:-3}"
export ARENA_MIN_SCORE_EDGE="${ARENA_MIN_SCORE_EDGE:-0.5}"
export MUZERO_LIVE_UNIVERSE_MAX_SYMBOLS="${MUZERO_LIVE_UNIVERSE_MAX_SYMBOLS:-12}"
export MUZERO_LIVE_TOP_SYMBOLS="${MUZERO_LIVE_TOP_SYMBOLS:-5}"
export MUZERO_LIVE_MIN_SYMBOL_EVAL_GAMES="${MUZERO_LIVE_MIN_SYMBOL_EVAL_GAMES:-2}"
export MUZERO_LIVE_MIN_SYMBOL_TRADES="${MUZERO_LIVE_MIN_SYMBOL_TRADES:-4}"
export MUZERO_LIVE_MIN_SYMBOL_RETURN_PCT="${MUZERO_LIVE_MIN_SYMBOL_RETURN_PCT:-0.0}"
export MUZERO_LIVE_MIN_SYMBOL_NET_REALIZED_PCT="${MUZERO_LIVE_MIN_SYMBOL_NET_REALIZED_PCT:-0.0}"
export MUZERO_LIVE_MIN_SYMBOL_PROFIT_FACTOR="${MUZERO_LIVE_MIN_SYMBOL_PROFIT_FACTOR:-1.0}"
export MUZERO_LIVE_MAX_SYMBOL_DRAWDOWN_PCT="${MUZERO_LIVE_MAX_SYMBOL_DRAWDOWN_PCT:-5.0}"
export MUZERO_LIVE_MIN_SYMBOL_LONG_ENTRY_SHARE="${MUZERO_LIVE_MIN_SYMBOL_LONG_ENTRY_SHARE:-0.10}"
export MUZERO_LIVE_MIN_SYMBOL_SHORT_ENTRY_SHARE="${MUZERO_LIVE_MIN_SYMBOL_SHORT_ENTRY_SHARE:-0.10}"
export MUZERO_LIVE_MAX_SYMBOL_DIRECTIONAL_IMBALANCE="${MUZERO_LIVE_MAX_SYMBOL_DIRECTIONAL_IMBALANCE:-0.85}"
export DREAMER_BATCH_SIZE="${DREAMER_BATCH_SIZE:-8}"
export DREAMER_SEQUENCE_LENGTH="${DREAMER_SEQUENCE_LENGTH:-64}"
export DREAMER_SEQUENCE_STRIDE="${DREAMER_SEQUENCE_STRIDE:-32}"
export DREAMER_MAX_START_STATES="${DREAMER_MAX_START_STATES:-256}"
export DREAMER_HIDDEN_STATE_SIZE="${DREAMER_HIDDEN_STATE_SIZE:-128}"
export DREAMER_NETWORK_HIDDEN_DIMS="${DREAMER_NETWORK_HIDDEN_DIMS:-256,256}"
export DREAMER_NUM_UNROLL_STEPS="${DREAMER_NUM_UNROLL_STEPS:-3}"
export DREAMER_REPLAY_MAX_GAMES="${DREAMER_REPLAY_MAX_GAMES:-2500}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
export JAX_PLATFORMS="${JAX_PLATFORMS:-cpu}"
export XLA_PYTHON_CLIENT_PREALLOCATE="${XLA_PYTHON_CLIENT_PREALLOCATE:-false}"
if [ -z "${XLA_PYTHON_CLIENT_MEM_FRACTION:-}" ]; then
  export XLA_PYTHON_CLIENT_MEM_FRACTION="0.05"
else
  export XLA_PYTHON_CLIENT_MEM_FRACTION
fi
export TRAINING_CHILD_CUDA_VISIBLE_DEVICES="${TRAINING_CHILD_CUDA_VISIBLE_DEVICES:-0}"
export TRAINING_CHILD_JAX_PLATFORMS="${TRAINING_CHILD_JAX_PLATFORMS:-cuda}"
export TRAINING_CHILD_XLA_PYTHON_CLIENT_PREALLOCATE="${TRAINING_CHILD_XLA_PYTHON_CLIENT_PREALLOCATE:-false}"
export TRAINING_CHILD_XLA_PYTHON_CLIENT_MEM_FRACTION="${TRAINING_CHILD_XLA_PYTHON_CLIENT_MEM_FRACTION:-0.85}"
export MUZERO_PROMOTION_MIN_TOTAL_TRADES="${MUZERO_PROMOTION_MIN_TOTAL_TRADES:-24}"
export MUZERO_PROMOTION_MIN_EVAL_GAMES="${MUZERO_PROMOTION_MIN_EVAL_GAMES:-12}"
export MUZERO_PROMOTION_MIN_EVAL_SYMBOLS="${MUZERO_PROMOTION_MIN_EVAL_SYMBOLS:-3}"
export MUZERO_PROMOTION_MIN_WIN_RATE="${MUZERO_PROMOTION_MIN_WIN_RATE:-50.0}"
export MUZERO_PROMOTION_MIN_RETURN_PCT="${MUZERO_PROMOTION_MIN_RETURN_PCT:-0.0}"
export MUZERO_PROMOTION_MIN_PROFIT_FACTOR="${MUZERO_PROMOTION_MIN_PROFIT_FACTOR:-1.05}"
export MUZERO_PROMOTION_MIN_EXPECTANCY_PCT="${MUZERO_PROMOTION_MIN_EXPECTANCY_PCT:-0.02}"
export MUZERO_PROMOTION_MAX_DRAWDOWN_PCT="${MUZERO_PROMOTION_MAX_DRAWDOWN_PCT:-4.0}"
export MUZERO_PROMOTION_MIN_POSITIVE_EPISODE_RATE="${MUZERO_PROMOTION_MIN_POSITIVE_EPISODE_RATE:-50.0}"
export MUZERO_PROMOTION_MIN_NET_REALIZED_PCT="${MUZERO_PROMOTION_MIN_NET_REALIZED_PCT:-0.50}"
export MUZERO_PROMOTION_MIN_SPLIT_EFFICIENCY="${MUZERO_PROMOTION_MIN_SPLIT_EFFICIENCY:-0.45}"
export MUZERO_PROMOTION_MIN_PYRAMID_EFFICIENCY="${MUZERO_PROMOTION_MIN_PYRAMID_EFFICIENCY:-0.45}"
export MUZERO_PROMOTION_MIN_SLBE_CAPTURE_RATE="${MUZERO_PROMOTION_MIN_SLBE_CAPTURE_RATE:-0.40}"
export MUZERO_PROMOTION_MAX_HOLD_DRAG_SCORE="${MUZERO_PROMOTION_MAX_HOLD_DRAG_SCORE:-0.40}"
export MUZERO_PROMOTION_MIN_CLOSE_QUALITY_SCORE="${MUZERO_PROMOTION_MIN_CLOSE_QUALITY_SCORE:-0.45}"
export TRAINING_TIMESCALE_ENABLED="${TRAINING_TIMESCALE_ENABLED:-1}"
export TRAINING_TIMESCALE_HOST="${TRAINING_TIMESCALE_HOST:-timescaledb}"
export TRAINING_TIMESCALE_PORT="${TRAINING_TIMESCALE_PORT:-5432}"
export TRAINING_TIMESCALE_DB="${TRAINING_TIMESCALE_DB:-thehive}"
export TRAINING_TIMESCALE_USER="${TRAINING_TIMESCALE_USER:-eva}"
export TRAINING_TIMESCALE_PASSWORD="${TRAINING_TIMESCALE_PASSWORD:-${TIMESCALE_PASSWORD:-devpassword}}"
export TRAINING_TIMESCALE_SSLMODE="${TRAINING_TIMESCALE_SSLMODE:-prefer}"
export TRAINING_TIMESCALE_BARS_TABLE="${TRAINING_TIMESCALE_BARS_TABLE:-market.market_bars}"
export TRAINING_TIMESCALE_FEATURES_TABLE="${TRAINING_TIMESCALE_FEATURES_TABLE:-market.market_features}"
export TRAINING_TIMESCALE_DATASETS_TABLE="${TRAINING_TIMESCALE_DATASETS_TABLE:-training.training_datasets}"
export TRAINING_TIMESCALE_ARENA_TABLE="${TRAINING_TIMESCALE_ARENA_TABLE:-training.arena_results}"
export TRAINING_TIMESCALE_GA_TABLE="${TRAINING_TIMESCALE_GA_TABLE:-training.ga_trials}"
export TRAINING_TIMESCALE_REPLAY_TABLE="${TRAINING_TIMESCALE_REPLAY_TABLE:-training.replay_metadata}"
export TRAINING_TIMESCALE_RUN_WINDOWS_TABLE="${TRAINING_TIMESCALE_RUN_WINDOWS_TABLE:-training.run_windows}"
export TIMESCALE_STORAGE_PROFILE="${TIMESCALE_STORAGE_PROFILE:-balanced}"
export HISTORY_TIMESCALE_ALLOWED_TIMEFRAMES="${HISTORY_TIMESCALE_ALLOWED_TIMEFRAMES:-M5,H1,D1}"
export TIMESCALE_DB_SOFT_LIMIT_GB="${TIMESCALE_DB_SOFT_LIMIT_GB:-120}"
export TIMESCALE_DB_HARD_LIMIT_GB="${TIMESCALE_DB_HARD_LIMIT_GB:-150}"
export TELEGRAM_NOTIFY_TRAINING="${TELEGRAM_NOTIFY_TRAINING:-1}"
export TRAINING_GA_STATUS="${TRAINING_GA_STATUS:-}"
export TRAINING_GA_GENERATION="${TRAINING_GA_GENERATION:-}"
export TRAINING_GA_TRIAL="${TRAINING_GA_TRIAL:-}"
export TRAINING_GA_CAMPAIGN_ID="${TRAINING_GA_CAMPAIGN_ID:-}"
export TRAINING_GA_SCOPE="${TRAINING_GA_SCOPE:-}"
export TRAINING_GA_PARENT_CHAMPION_ID="${TRAINING_GA_PARENT_CHAMPION_ID:-}"
export TRAINING_GA_DEFER_PROMOTION="${TRAINING_GA_DEFER_PROMOTION:-}"
export TRAINING_GA_GENOME_JSON="${TRAINING_GA_GENOME_JSON:-}"
export TRAINING_GA_SEED_CHECKPOINT_PATH="${TRAINING_GA_SEED_CHECKPOINT_PATH:-}"
export TRAINING_GATE_PROFILE="${TRAINING_GATE_PROFILE:-}"
export TRAINING_FOCUS_SYMBOLS="${TRAINING_FOCUS_SYMBOLS:-}"
export TRAINING_RESUME_CHECKPOINT_PATH="${TRAINING_RESUME_CHECKPOINT_PATH:-}"
export TRAINING_RESUME_STEP="${TRAINING_RESUME_STEP:-}"
export TRAINING_SEQUENCE_ID="${TRAINING_SEQUENCE_ID:-}"
export TRAINING_SEQUENCE_PROFILE="${TRAINING_SEQUENCE_PROFILE:-}"
export TRAINING_WINDOW_ID="${TRAINING_WINDOW_ID:-}"
export TRAINING_TRIAL_ID="${TRAINING_TRIAL_ID:-}"
export TRAINING_SUPERVISOR_STATE="${TRAINING_SUPERVISOR_STATE:-}"

if [ "$REBUILD_TRAINER_IMAGE" = "1" ]; then
  echo "[nightly] Reconstruction de l'image eva-trainer"
  emit_training_log INFO launcher "Reconstruction de l'image eva-trainer."
  if ! docker compose --progress plain build eva-trainer; then
    echo "[nightly] Build eva-trainer en echec, poursuite avec l'image existante"
    emit_training_log WARNING launcher "Build eva-trainer en echec, poursuite avec l'image existante."
  fi
fi

echo "[nightly] Installation runtime JAX CUDA validee"
emit_launcher_state "trainer_running" "$([ "$VLLM_STOPPED" = "1" ] && echo stopped_for_training || echo online)" "$([ "$COMFYUI_STOPPED" = "1" ] && echo stopped_for_training || echo online)"
emit_training_log INFO launcher "Demarrage du conteneur trainer pour le run nightly."
docker compose run --rm   -e PYTHONPATH=/app/eva-lab:/app/shared   -e TRAINING_PROFILE="$TRAINING_PROFILE"   -e TRAINING_AUTOMATION_MODE="$TRAINING_AUTOMATION_MODE"   -e TRAINING_REFRESH_AFTER_HOURS="${TRAINING_REFRESH_AFTER_HOURS:-24}"   -e TRAINING_MAX_CHAMPION_AGE_HOURS="${TRAINING_MAX_CHAMPION_AGE_HOURS:-72}"   -e TRAINING_MIN_SHADOW_RECORDS="${TRAINING_MIN_SHADOW_RECORDS:-25}"   -e CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES"   -e JAX_PLATFORMS="$JAX_PLATFORMS"   -e XLA_PYTHON_CLIENT_PREALLOCATE="$XLA_PYTHON_CLIENT_PREALLOCATE"   -e XLA_PYTHON_CLIENT_MEM_FRACTION="$XLA_PYTHON_CLIENT_MEM_FRACTION"   -e TRAINING_CHILD_CUDA_VISIBLE_DEVICES="$TRAINING_CHILD_CUDA_VISIBLE_DEVICES"   -e TRAINING_CHILD_JAX_PLATFORMS="$TRAINING_CHILD_JAX_PLATFORMS"   -e TRAINING_CHILD_XLA_PYTHON_CLIENT_PREALLOCATE="$TRAINING_CHILD_XLA_PYTHON_CLIENT_PREALLOCATE"   -e TRAINING_CHILD_XLA_PYTHON_CLIENT_MEM_FRACTION="$TRAINING_CHILD_XLA_PYTHON_CLIENT_MEM_FRACTION"   -e REBUILD_TRAINER_IMAGE="$REBUILD_TRAINER_IMAGE"   -e RUN_TRAIN_GNN="$RUN_TRAIN_GNN"   -e RUN_TRAIN_MUZERO="$RUN_TRAIN_MUZERO"   -e RUN_TRAIN_DREAMER="$RUN_TRAIN_DREAMER"   -e TRAINING_ENGINE="$TRAINING_ENGINE"   -e TRAINING_TRIAL_MODE="$TRAINING_TRIAL_MODE"   -e TRAINING_TRIAL_COST_PROFILE="$TRAINING_TRIAL_COST_PROFILE"   -e MUZERO_HORIZONS="$MUZERO_HORIZONS"   -e DREAMER_HORIZON="$DREAMER_HORIZON"   -e DREAMER_DEFAULT_HORIZON="$DREAMER_DEFAULT_HORIZON"   -e DREAMER_EPOCHS="$DREAMER_EPOCHS"   -e TRAIN_GNN_EPOCHS="$TRAIN_GNN_EPOCHS"   -e TRAIN_GNN_BATCH_SIZE="$TRAIN_GNN_BATCH_SIZE"   -e TRAIN_GNN_CHECKPOINT_EVERY="$TRAIN_GNN_CHECKPOINT_EVERY"   -e TRAIN_GNN_SYMBOLS="$TRAIN_GNN_SYMBOLS"   -e TRAIN_GNN_FOCUS_SYMBOL="$TRAIN_GNN_FOCUS_SYMBOL"   -e TRAIN_GNN_CONTEXT_SYMBOLS="$TRAIN_GNN_CONTEXT_SYMBOLS"   -e TRAIN_GNN_DEPLOYMENT_CLASS="$TRAIN_GNN_DEPLOYMENT_CLASS"   -e MUZERO_TRAINING_STEPS="$MUZERO_TRAINING_STEPS"   -e MUZERO_GAMES_PER_SYMBOL="$MUZERO_GAMES_PER_SYMBOL"   -e MUZERO_BATCH_SIZE="$MUZERO_BATCH_SIZE"   -e MUZERO_NUM_SIMULATIONS="$MUZERO_NUM_SIMULATIONS"   -e MUZERO_COLLECTION_NUM_SIMULATIONS="$MUZERO_COLLECTION_NUM_SIMULATIONS"   -e MUZERO_COLLECTION_NUM_SIMULATIONS_METALS="$MUZERO_COLLECTION_NUM_SIMULATIONS_METALS"   -e MUZERO_COLLECTION_NUM_SIMULATIONS_XAUUSD="$MUZERO_COLLECTION_NUM_SIMULATIONS_XAUUSD"   -e MUZERO_COLLECTION_MAX_MOVES="$MUZERO_COLLECTION_MAX_MOVES"   -e MUZERO_COLLECTION_MAX_MOVES_METALS="$MUZERO_COLLECTION_MAX_MOVES_METALS"   -e MUZERO_COLLECTION_MAX_MOVES_XAUUSD="$MUZERO_COLLECTION_MAX_MOVES_XAUUSD"   -e MUZERO_COLLECTION_MAX_EPISODE_SECONDS_METALS="$MUZERO_COLLECTION_MAX_EPISODE_SECONDS_METALS"   -e MUZERO_COLLECTION_MAX_EPISODE_SECONDS_XAUUSD="$MUZERO_COLLECTION_MAX_EPISODE_SECONDS_XAUUSD"   -e MUZERO_COLLECTION_PARALLEL_GAMES="$MUZERO_COLLECTION_PARALLEL_GAMES"   -e MUZERO_ROOT_EXPLORATION_FRACTION="$MUZERO_ROOT_EXPLORATION_FRACTION"   -e MUZERO_PB_C_INIT="$MUZERO_PB_C_INIT"   -e MUZERO_REANALYZE_EVERY_STEPS="$MUZERO_REANALYZE_EVERY_STEPS"   -e MUZERO_REANALYZE_MAX_GAMES="$MUZERO_REANALYZE_MAX_GAMES"   -e MUZERO_REANALYZE_MAX_POSITIONS_PER_GAME="$MUZERO_REANALYZE_MAX_POSITIONS_PER_GAME"   -e MUZERO_REANALYZE_NUM_SIMULATIONS="$MUZERO_REANALYZE_NUM_SIMULATIONS"   -e MUZERO_MAX_MOVES="$MUZERO_MAX_MOVES"   -e MUZERO_MAX_SYMBOLS="$MUZERO_MAX_SYMBOLS"   -e MUZERO_MODEL_FAMILY="$MUZERO_MODEL_FAMILY"   -e MUZERO_DATASET_SOURCE="$MUZERO_DATASET_SOURCE"   -e MUZERO_SYMBOLS="$MUZERO_SYMBOLS"   -e MUZERO_SYMBOLS_SCALP="$MUZERO_SYMBOLS_SCALP"   -e MUZERO_SYMBOLS_INTRADAY="$MUZERO_SYMBOLS_INTRADAY"   -e MUZERO_SYMBOLS_SWING="$MUZERO_SYMBOLS_SWING"   -e TRAINING_SYMBOLS="$TRAINING_SYMBOLS"   -e ARENA_MAX_SYMBOLS="$ARENA_MAX_SYMBOLS"   -e ARENA_SYMBOLS="$ARENA_SYMBOLS"   -e ARENA_SYMBOLS_SCALP="$ARENA_SYMBOLS_SCALP"   -e ARENA_SYMBOLS_INTRADAY="$ARENA_SYMBOLS_INTRADAY"   -e ARENA_SYMBOLS_SWING="$ARENA_SYMBOLS_SWING"   -e ARENA_GAMES_PER_SYMBOL="$ARENA_GAMES_PER_SYMBOL"   -e ARENA_MIN_GAMES="$ARENA_MIN_GAMES"   -e ARENA_MIN_SYMBOLS="$ARENA_MIN_SYMBOLS"   -e ARENA_MIN_SCORE_EDGE="$ARENA_MIN_SCORE_EDGE"   -e MUZERO_LIVE_UNIVERSE_MAX_SYMBOLS="$MUZERO_LIVE_UNIVERSE_MAX_SYMBOLS"   -e MUZERO_LIVE_TOP_SYMBOLS="$MUZERO_LIVE_TOP_SYMBOLS"   -e MUZERO_LIVE_MIN_SYMBOL_EVAL_GAMES="$MUZERO_LIVE_MIN_SYMBOL_EVAL_GAMES"   -e MUZERO_LIVE_MIN_SYMBOL_TRADES="$MUZERO_LIVE_MIN_SYMBOL_TRADES"   -e MUZERO_LIVE_MIN_SYMBOL_RETURN_PCT="$MUZERO_LIVE_MIN_SYMBOL_RETURN_PCT"   -e MUZERO_LIVE_MIN_SYMBOL_NET_REALIZED_PCT="$MUZERO_LIVE_MIN_SYMBOL_NET_REALIZED_PCT"   -e MUZERO_LIVE_MIN_SYMBOL_PROFIT_FACTOR="$MUZERO_LIVE_MIN_SYMBOL_PROFIT_FACTOR"   -e MUZERO_LIVE_MAX_SYMBOL_DRAWDOWN_PCT="$MUZERO_LIVE_MAX_SYMBOL_DRAWDOWN_PCT"   -e MUZERO_LIVE_MIN_SYMBOL_LONG_ENTRY_SHARE="$MUZERO_LIVE_MIN_SYMBOL_LONG_ENTRY_SHARE"   -e MUZERO_LIVE_MIN_SYMBOL_SHORT_ENTRY_SHARE="$MUZERO_LIVE_MIN_SYMBOL_SHORT_ENTRY_SHARE"   -e MUZERO_LIVE_MAX_SYMBOL_DIRECTIONAL_IMBALANCE="$MUZERO_LIVE_MAX_SYMBOL_DIRECTIONAL_IMBALANCE"   -e DREAMER_BATCH_SIZE="$DREAMER_BATCH_SIZE"   -e DREAMER_SEQUENCE_LENGTH="$DREAMER_SEQUENCE_LENGTH"   -e DREAMER_SEQUENCE_STRIDE="$DREAMER_SEQUENCE_STRIDE"   -e DREAMER_MAX_START_STATES="$DREAMER_MAX_START_STATES"   -e DREAMER_HIDDEN_STATE_SIZE="$DREAMER_HIDDEN_STATE_SIZE"   -e DREAMER_NETWORK_HIDDEN_DIMS="$DREAMER_NETWORK_HIDDEN_DIMS"   -e DREAMER_NUM_UNROLL_STEPS="$DREAMER_NUM_UNROLL_STEPS"   -e DREAMER_REPLAY_MAX_GAMES="$DREAMER_REPLAY_MAX_GAMES"   -e MUZERO_PROMOTION_MIN_TOTAL_TRADES="$MUZERO_PROMOTION_MIN_TOTAL_TRADES"   -e MUZERO_PROMOTION_MIN_EVAL_GAMES="$MUZERO_PROMOTION_MIN_EVAL_GAMES"   -e MUZERO_PROMOTION_MIN_EVAL_SYMBOLS="$MUZERO_PROMOTION_MIN_EVAL_SYMBOLS"   -e MUZERO_PROMOTION_MIN_WIN_RATE="$MUZERO_PROMOTION_MIN_WIN_RATE"   -e MUZERO_PROMOTION_MIN_RETURN_PCT="$MUZERO_PROMOTION_MIN_RETURN_PCT"   -e MUZERO_PROMOTION_MIN_PROFIT_FACTOR="$MUZERO_PROMOTION_MIN_PROFIT_FACTOR"   -e MUZERO_PROMOTION_MIN_EXPECTANCY_PCT="$MUZERO_PROMOTION_MIN_EXPECTANCY_PCT"   -e MUZERO_PROMOTION_MAX_DRAWDOWN_PCT="$MUZERO_PROMOTION_MAX_DRAWDOWN_PCT"   -e MUZERO_PROMOTION_MIN_POSITIVE_EPISODE_RATE="$MUZERO_PROMOTION_MIN_POSITIVE_EPISODE_RATE"   -e MUZERO_PROMOTION_MIN_NET_REALIZED_PCT="$MUZERO_PROMOTION_MIN_NET_REALIZED_PCT"   -e MUZERO_PROMOTION_MIN_SPLIT_EFFICIENCY="$MUZERO_PROMOTION_MIN_SPLIT_EFFICIENCY"   -e MUZERO_PROMOTION_MIN_PYRAMID_EFFICIENCY="$MUZERO_PROMOTION_MIN_PYRAMID_EFFICIENCY"   -e MUZERO_PROMOTION_MIN_SLBE_CAPTURE_RATE="$MUZERO_PROMOTION_MIN_SLBE_CAPTURE_RATE"   -e MUZERO_PROMOTION_MAX_HOLD_DRAG_SCORE="$MUZERO_PROMOTION_MAX_HOLD_DRAG_SCORE"   -e MUZERO_PROMOTION_MIN_CLOSE_QUALITY_SCORE="$MUZERO_PROMOTION_MIN_CLOSE_QUALITY_SCORE"   -e TRAINING_TIMESCALE_ENABLED="$TRAINING_TIMESCALE_ENABLED"   -e TRAINING_TIMESCALE_HOST="$TRAINING_TIMESCALE_HOST"   -e TRAINING_TIMESCALE_PORT="$TRAINING_TIMESCALE_PORT"   -e TRAINING_TIMESCALE_DB="$TRAINING_TIMESCALE_DB"   -e TRAINING_TIMESCALE_USER="$TRAINING_TIMESCALE_USER"   -e TRAINING_TIMESCALE_PASSWORD="$TRAINING_TIMESCALE_PASSWORD"   -e TRAINING_TIMESCALE_SSLMODE="$TRAINING_TIMESCALE_SSLMODE"   -e TRAINING_TIMESCALE_BARS_TABLE="$TRAINING_TIMESCALE_BARS_TABLE"   -e TRAINING_TIMESCALE_FEATURES_TABLE="$TRAINING_TIMESCALE_FEATURES_TABLE"   -e TRAINING_TIMESCALE_DATASETS_TABLE="$TRAINING_TIMESCALE_DATASETS_TABLE"   -e TRAINING_TIMESCALE_ARENA_TABLE="$TRAINING_TIMESCALE_ARENA_TABLE"   -e TRAINING_TIMESCALE_GA_TABLE="$TRAINING_TIMESCALE_GA_TABLE"   -e TRAINING_TIMESCALE_REPLAY_TABLE="$TRAINING_TIMESCALE_REPLAY_TABLE"   -e TRAINING_TIMESCALE_RUN_WINDOWS_TABLE="$TRAINING_TIMESCALE_RUN_WINDOWS_TABLE"   -e TIMESCALE_STORAGE_PROFILE="$TIMESCALE_STORAGE_PROFILE"   -e HISTORY_TIMESCALE_ALLOWED_TIMEFRAMES="$HISTORY_TIMESCALE_ALLOWED_TIMEFRAMES"   -e TIMESCALE_DB_SOFT_LIMIT_GB="$TIMESCALE_DB_SOFT_LIMIT_GB"   -e TIMESCALE_DB_HARD_LIMIT_GB="$TIMESCALE_DB_HARD_LIMIT_GB"   -e TELEGRAM_NOTIFY_TRAINING="$TELEGRAM_NOTIFY_TRAINING"   -e TRAINING_GA_STATUS="$TRAINING_GA_STATUS"   -e TRAINING_GA_GENERATION="$TRAINING_GA_GENERATION"   -e TRAINING_GA_TRIAL="$TRAINING_GA_TRIAL"   -e TRAINING_GA_CAMPAIGN_ID="$TRAINING_GA_CAMPAIGN_ID"   -e TRAINING_GA_SCOPE="$TRAINING_GA_SCOPE"   -e TRAINING_GA_PARENT_CHAMPION_ID="$TRAINING_GA_PARENT_CHAMPION_ID"   -e TRAINING_GA_DEFER_PROMOTION="$TRAINING_GA_DEFER_PROMOTION"   -e TRAINING_GA_GENOME_JSON="$TRAINING_GA_GENOME_JSON"   -e TRAINING_GA_SEED_CHECKPOINT_PATH="$TRAINING_GA_SEED_CHECKPOINT_PATH"   -e TRAINING_GATE_PROFILE="$TRAINING_GATE_PROFILE"   -e TRAINING_FOCUS_SYMBOLS="$TRAINING_FOCUS_SYMBOLS"   -e TRAINING_RESUME_CHECKPOINT_PATH="$TRAINING_RESUME_CHECKPOINT_PATH"   -e TRAINING_RESUME_STEP="$TRAINING_RESUME_STEP"   -e TRAINING_SEQUENCE_ID="$TRAINING_SEQUENCE_ID"   -e TRAINING_SEQUENCE_PROFILE="$TRAINING_SEQUENCE_PROFILE"   -e TRAINING_WINDOW_ID="$TRAINING_WINDOW_ID"   -e TRAINING_TRIAL_ID="$TRAINING_TRIAL_ID"   -e TRAINING_SUPERVISOR_STATE="$TRAINING_SUPERVISOR_STATE"   -e TRAINING_RUN_TRIGGER="$RUN_TRIGGER"   -e NIGHTLY_RUN_LOCK_ALREADY_HELD="1"   -v "$PROJECT_DIR/data:/app/eva-lab/data"   eva-trainer   bash -lc "python -c 'import importlib.metadata as md; import jax, haiku, optax, chex, flax, orbax.checkpoint; print(\"[nightly] jax\", jax.__version__); print(\"[nightly] jaxlib\", md.version(\"jaxlib\")); print(\"[nightly] haiku\", haiku.__version__); print(\"[nightly] optax\", optax.__version__); print(\"[nightly] chex\", chex.__version__); print(\"[nightly] flax\", flax.__version__); print(\"[nightly] backend\", jax.default_backend()); print(\"[nightly] devices\", jax.devices())' || pip install --no-cache-dir --upgrade jax==0.4.23 jaxlib==0.4.23+cuda11.cudnn86 dm-haiku==0.0.11 optax==0.1.7 chex==0.1.85 flax==0.8.4 orbax-checkpoint==0.5.16 nest_asyncio==1.6.0 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html && python scripts/train_nightly_stack.py" &
TRAINER_RUN_PID=$!
TRAINER_CONTAINER_NAME=""
for attempt in $(seq 1 20); do
  TRAINER_CONTAINER_NAME="$(list_active_trainer_containers | tail -n 1)"
  if [ -n "$TRAINER_CONTAINER_NAME" ]; then
    emit_launcher_state "trainer_running"       "$([ "$VLLM_STOPPED" = "1" ] && echo stopped_for_training || echo online)"       "$([ "$COMFYUI_STOPPED" = "1" ] && echo stopped_for_training || echo online)"       "$TRAINER_CONTAINER_NAME"
    break
  fi
  sleep 2
done
wait "$TRAINER_RUN_PID"
