version: '3.8'

services:
  comfyui:
    image: tzwm/comfyui:cu121
    container_name: eva_comfyui
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - /mnt/data/comfyui/output:/workspace/ComfyUI/output
      - /mnt/data/comfyui/input:/workspace/ComfyUI/input
      - /mnt/data/comfyui/models:/workspace/ComfyUI/models
      - /mnt/data/comfyui/custom_nodes:/workspace/ComfyUI/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - CLI_ARGS=--listen 0.0.0.0 --port 8188
