"""
Shared - modeles et utilitaires partages THE HIVE.
"""

from shared.models import (
    AccountBalance,
    AgentMessage,
    AgentMessageType,
    AgentStatus,
    AuditRecord,
    BaseHealthResponse,
    ChatMessage,
    ConnectorMode,
    CopyTradeRequest,
    CopyTradeResult,
    EventEnvelope,
    ExecutionEventEnvelope,
    GPUMetrics,
    HardwareMetrics,
    HydraAccountRole,
    HydraEventType,
    HydraJobStatus,
    HydraReplicationJob,
    HydraScalingMode,
    HydraTerminalHealth,
    Intent,
    IntentType,
    InvestmentThesisEnvelope,
    MarketContextEnvelope,
    MessageRole,
    OrderSource,
    OrderType,
    Position,
    PromotionReportEnvelope,
    PropFirmAccount,
    RiskStatus,
    RuntimeMode,
    SecurityEvent,
    SecuritySeverity,
    TradeReplicationEvent,
    TradeAction,
    TradeOrder,
    TradingContextEnvelope,
    TradingDecisionEnvelope,
    TrainingRunEnvelope,
)
from shared.math_ops import calculate_cvar, calculate_var, inv_symlog, symlog
from shared.config import Settings, get_settings
from shared.telemetry import Telemetry
from shared.circuit_breaker import CircuitBreaker, CircuitBreakerOpenError
from shared.grpc_client import SwarmGRPCClient

__all__ = [
    "AccountBalance",
    "AgentMessage",
    "AgentMessageType",
    "AgentStatus",
    "AuditRecord",
    "BaseHealthResponse",
    "ChatMessage",
    "CircuitBreaker",
    "CircuitBreakerOpenError",
    "ConnectorMode",
    "CopyTradeRequest",
    "CopyTradeResult",
    "EventEnvelope",
    "ExecutionEventEnvelope",
    "GPUMetrics",
    "HardwareMetrics",
    "HydraAccountRole",
    "HydraEventType",
    "HydraJobStatus",
    "HydraReplicationJob",
    "HydraScalingMode",
    "HydraTerminalHealth",
    "Intent",
    "IntentType",
    "InvestmentThesisEnvelope",
    "MarketContextEnvelope",
    "MessageRole",
    "OrderSource",
    "OrderType",
    "Position",
    "PromotionReportEnvelope",
    "PropFirmAccount",
    "RiskStatus",
    "RuntimeMode",
    "SecurityEvent",
    "SecuritySeverity",
    "Settings",
    "SwarmGRPCClient",
    "Telemetry",
    "TradeReplicationEvent",
    "TradeAction",
    "TradeOrder",
    "TradingContextEnvelope",
    "TradingDecisionEnvelope",
    "TrainingRunEnvelope",
    "calculate_cvar",
    "calculate_var",
    "get_settings",
    "inv_symlog",
    "symlog",
]
